### ISSUE TITLE
関係ない通知をツイートしてしまう

### ISSUE THREAD

**Issue by yamagami2211** [Siketyan/SilicaGel#16]
GooglePlayミュージックにて。
DeployGate

1,google play musicに追加しました
https://twitter.com/yamagami2211/status/981686609060904960

2,ダウンロードしています...
https://twitter.com/yamagami2211/status/981686632913944576

3,ダウンロードが完了しました
https://twitter.com/yamagami2211/status/981686650546798593

**Comment by nirot1r** [comment]
対応します。

**Comment by mak0tia** [comment]
同じくGooglePlay ミュージックにて
 https://twitter.com/hs6a/status/985641710079303681
 https://twitter.com/hs6a/status/985641711429763072
