### ISSUE TITLE
403エラーが出る

### ISSUE THREAD

**Issue by yamagami2211** [Siketyan/SilicaGel#18]
403:The request is understood, but it has been refused
https://i.gyazo.com/a10138127920e49b0ef120b5629fa14a.png

**Comment by cuezaku** [comment]
同様の現象が数日前から発生しています。
![screenshot_20190118-160353](https://user-images.githubusercontent.com/46817120/51389797-cfe9bd80-1b70-11e9-98f1-f7443452821d.png)
![screenshot_20190118-160855](https://user-images.githubusercontent.com/46817120/51389886-14755900-1b71-11e9-9c0e-4ea8e209c8a8.png)

**Comment by cuezaku** [comment]
先ほど0:50頃Spotifyを再生したところ、正常に曲情報のツイート、トゥートが行われました。
403エラーが出なくなった原因が不明なので詳しい報告ができず申し訳ありません。
お騒がせいたしました。

**Comment by Siketyan** [comment]
すいません、先程までAPIに書き込み制限がかかっておりました。ご迷惑をおかけし、申し訳ありません。

**Comment by Siketyan** [comment]
再び凍結されてしまったので，ソーシャルプロキシの作成を検討中です．

**Comment by Siketyan** [comment]
Social Proxyへ対応したのでクローズします．
