### ISSUE TITLE
DeployGateでの配布

### ISSUE THREAD

**Issue by mak0tia** [Siketyan/SilicaGel#9]
毎回APKをReleaseから落としてくるのがクソだるいのでDeployGateかどこかに投げてユーザーは更新するだけでいいようにして

**Comment by Siketyan** [comment]
Google Play で配布できないか、プロ生 さんに打診中

**Comment by mak0tia** [comment]
なるほどね?
それまでとりあえずDeployGateの配布用リンクぶん投げておいて

**Comment by Siketyan** [comment]
https://dply.me/nr6yvg
